### ISSUE TITLE
Use both `yup` and `react-use-form-state` for form validation?

### ISSUE THREAD

**Issue by estyxx** [pythonitalia/pycon#1186]
We started to use `react-use-form-state` that has a nice hook that simplifies managing form state. It has some properties to manage custom validation and very easy access to the validity/errors of the form. 

`formState` is like 
```
{
  validity: {
    password: false,
  },
  errors: {
    password: 'Password is not strong enough',
  }
}
```

But, the problem is that *if an input isn't touched and the user tries to submit, that field won't be validated*! There is a specific [issue](https://github.com/wsmd/react-use-form-state/issues/56) for that problem. 
Someone tries to provide an alternative [fix](https://github.com/wsmd/react-use-form-state/issues/56#issuecomment-487807923), I did a little try in a component but I was struggling with this error: `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?` (I think the React changed, now requires a different way to pass ref...) 
So I'm not such expert to understand how to fix this error or understand if it could fit in our component...) 

Yup is a valid alternative, but you have to set errors after invoking the validation, and it doesn't manage the state. 

I will prefer to use only one library if is it possible... but I have the feeling that both are _not complete_. 
I think untily we don't find a solution to validate on submit with `react-use-form-state` we have to use both and sets `validity` and `errors` manually after invoke `yup` validation. 

```
  const setFormsErrors = () => {
    schema
      .validate(formState.values, { abortEarly: false })
      .then(value => {
        formState.validity = {};
        formState.errors = {};
      })
      .catch(err => {
        const newErrors = {};
        err.inner.forEach(item => {          
           formState.setFieldError(item.path, item.message);
        });
      });
  };
```

In that way, if we solve our little problem (or a `react-use-form-state`'s major realise will integrate that possibility) we could remove yup as it will no longer be necessary...

**Comment by patrick91** [comment]
We could try this as well :) https://react-hook-form.com/
