### ISSUE TITLE
Send emails to selected user from the Newsletter admin panel

### ISSUE THREAD

**Issue by estyxx** [pythonitalia/pycon#1399]
Put a form in the admin panel to schedule/send an email to send to specific recipients/users

1. Send to all newsletter subscriber 

Other recipients could be:
2. Speaker without ticket 
3. Users that didn't fill their ticket (maybe this is not necessary with prefix)
4. users who bought the ticket. 
5. Speakers that didn't fill their ticket

**Comment by marcoacierno** [comment]
we can discuss the newsletter here #1969
