### ISSUE TITLE
Add delete button to proposed talks

### ISSUE THREAD

**Issue by switowski** [pythonitalia/pycon#1406]
Hello,

I have just submitted my first talk proposal (🎉 ), but I had an issue that can probably be easily fixed and make life for others easier. The "ABSTRACT" field doesn't say anywhere that it should be max 1000 characters and when you press "Submit" nothing happens, except a black text appears under the abstract saying that it's too long. But this text is very hard to notice. Could you maybe make it at least red and show an error message when user tries to submit (I thought that submit button is not working and it took me 3 tries, including a different browser until I found the error message)? 

Also, is it possible to edit or delete a proposal? How should I proceed in case I want to update my proposals?

![Make_a_proposal___PyCon_Italy](https://user-images.githubusercontent.com/4835412/70854022-6bd19580-1eb6-11ea-8dd2-8b3b926af20d.png)

**Comment by patrick91** [comment]
I think everything should be handled in this PR: https://github.com/pythonitalia/pycon/pull/1388

I'm going to review it soon :)

**Comment by patrick91** [comment]
Merged :) I'll keep this open as we don't have a delete button at the moment :)

**Comment by marcoacierno** [comment]
thanks for the report! 🙌 I assigned the issue to myself as will have a look at the "delete" button later today
