### ISSUE TITLE
When editing a talk, length is set to a default value

### ISSUE THREAD

**Issue by switowski** [pythonitalia/pycon#1423]
Hello again :)

there seems to be a small bug with the edit functionality. Each time I try to edit one of my talks - the length of the talk is being set to the default value (60 minutes) instead of whatever value I set before (see the attached GIF - my talk had length of 45 minutes but when I edit it, it's automatically set to 60 minutes).

![editbug](https://user-images.githubusercontent.com/4835412/71244810-a783b980-2313-11ea-8653-1b0f59e067a0.gif)

**Comment by patrick91** [comment]
Well spotted! Thanks a lot :D
