### ISSUE TITLE
Tickets page broken after poking with the cart

### ISSUE THREAD

**Issue by xrmx** [pythonitalia/pycon#1490]
Hello, the tickets page now gives me the Dawson page. I don't remember precisely how to reproduce but something around these steps:
- as an anonymous user open the tickets page
- add something to the cart (2 business tickets and a room)
- click next
- click browser back button

I'm on mobile chrome.

Thanks!

**Comment by xrmx** [comment]
And here's the error:

TypeError: t.checkin.toDate is not a function

**Comment by marcoacierno** [comment]
Thanks for the report! The fix should be live in about 10 minutes!

**Comment by xrmx** [comment]
@marcoacierno thanks!
