### ISSUE TITLE
Association

### ISSUE THREAD

**Issue by simobasso** [pythonitalia/pycon#17]
We need to provide an application to manage our members, this is mainly for the Python Italia association, but it is directly linked to attendees of the conference, we don't need to make a separate site/application for this.

Goals:

1. Keep track of all the members
2. Allow members to renew their subscription (maybe allowing automated renewal as well)
3. Allow anyone to become a member
4. Allow donations (maybe this is out of scope)
5. Allow users to opt-in to job offers.
6. Allow users to specify their location/city

TODO:

- [x] member
- [ ] donation
- [ ] payment
- [ ] other

**Comment by patrick91** [comment]
TODO: there should be a way to mark the founders since they don't have to pay the quote until 2028

**Comment by patrick91** [comment]
Closing this for now, we will revisit association stuff in future :)
