### ISSUE TITLE
Sign up - Add space between "FULLNAME" so it is FULL NAME & Check the placeholder text

### ISSUE THREAD

**Issue by nafeesa3** [pythonitalia/pycon#3373]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/98463499/225686388-7d5b3470-f604-4a6b-b125-203cdd020450.png">

also check the placeholder text
<img width="768" alt="image" src="https://user-images.githubusercontent.com/98463499/225686684-480c79c7-b16f-4ab8-82bf-5df2c69c96db.png">

**Comment by marcoacierno** [comment]
Not sure what you are referring to with placeholder text, text full name has been changed
