### ISSUE TITLE
Sign Out screen [desktop/mobile] - 1. Review CTA button against design 2. Change messaging to user's first name 

### ISSUE THREAD

**Issue by nafeesa3** [pythonitalia/pycon#3402]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/98463499/227501826-05f40ef8-7238-4b23-9293-e53f2db006ca.png">

<img width="303" alt="image" src="https://user-images.githubusercontent.com/98463499/227502037-d102757e-9212-4171-892c-21b48410b230.png">

<img width="886" alt="image" src="https://user-images.githubusercontent.com/98463499/227501925-44b6ca6c-c752-4b20-84aa-f941da044097.png">

**Comment by marcoacierno** [comment]
I think it uses the fullname if the name is not set! Try setting a name and let me know if you still replicate it
