### ISSUE TITLE
Buy Tickets - Add the python tail

### ISSUE THREAD

**Issue by nafeesa3** [pythonitalia/pycon#3403]
design - 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/98463499/227505455-a2ccb1c6-f92b-49e7-b18a-c6b8f2807386.png">

live site - 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/98463499/227505837-6f936deb-bc3f-40fe-9c88-dd0d1ee47e92.png">

**Comment by marcoacierno** [comment]
We should discuss the back arrow button, I don't really like it. I will create a different ticket for it
