### ISSUE TITLE
Importer

### ISSUE THREAD

**Issue by patrick91** [pythonitalia/pycon#35]
we need a way to import data from the old site to this one

**Comment by greenkey** [comment]
Entities to import:

- [x] User
- [ ] AudienceLevel
- [ ] Conference
- [ ] Deadline
- [ ] Duration
- [ ] Language
- [ ] Order
- [ ] OrderItem
- [ ] Room
- [ ] ScheduleItem
- [ ] Submission
- [ ] SubmissionType
- [ ] TicketFare
- [ ] Ticket
- [ ] Topic
