### ISSUE TITLE
Website crashing on Photo Upload

### ISSUE THREAD

**Issue by sansyrox** [pythonitalia/pycon#3655]
<img width="1121" alt="image" src="https://github.com/pythonitalia/pycon/assets/29942790/510dcfb0-f90e-4108-9626-82279e8b338a">

**Comment by marcoacierno** [comment]
Hello @sansyrox!

can you share more info? In what page is this?

**Comment by marcoacierno** [comment]
We got more reports and figured out it was connected to users uploading avatars bigger than 1MB.

This was fixed a few days ago in 3b5118b5071e0f6e3fcef816fca4aaafb67b687a
