### ISSUE TITLE
Accessibility information LINK broken in "How to reach the conference" page

### ISSUE THREAD

**Issue by dostogircse171** [pythonitalia/pycon#3685]
I found a link is broken and going 404 when click. 
That is in this page: [How to reach the conference](https://2024.pycon.it/en/where) under "By Train" Accordion. 

**The correct link should be this** https://www.at-bus.it/en/lines-and-timetables/prm

<img width="1027" alt="Screenshot at Jan 17 5-59-29 pm" src="https://github.com/pythonitalia/pycon/assets/28702192/313fd2e1-064a-459c-bba3-b74496fb6ea4">

**Comment by marcoacierno** [comment]
Thank you! 🙏 I fixed it now
