### ISSUE TITLE
ti.to integration

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#387]
- Where should we create the conference tickets? On ti.to and then sync the backend or create them on the backend and then syncing ti.to?

- It would be great if the normal flow could not be interrupted by ti.to, I was thinking to have something similar to PayPal, the user selects what ticket he/she wants and then clicks on 'Pay', we will redirect the user to ti.to for the payment and then when done the user will be redirected back to the order page in our site

**Comment by patrick91** [comment]
> Where should we create the conference tickets? On ti.to and then sync the backend or create them on the backend and then syncing ti.to?

I'd say on our backend/admin as a "nice to have" feature, we can keep them on ti.to for the time being (so we don't have to implement the feature of adding tickets, at least for an initial release).

> It would be great if the normal flow could not be interrupted by ti.to, I was thinking to have something similar to PayPal, the user selects what ticket he/she wants and then clicks on 'Pay', we will redirect the user to ti.to for the payment and then when done the user will be redirected back to the order page in our site

That should be possible: https://ti.to/docs/integrations

:D

**Comment by matlaparterre** [comment]
>     * Where should we create the conference tickets? On ti.to and then sync the backend 

Yes this should be the procedure now. 

> or create them on the backend and then syncing ti.to?

Maybe later we could think of upgrade this

> 
>     * It would be great if the normal flow could not be interrupted by ti.to, I was thinking to have something similar to PayPal, the user selects what ticket he/she wants and then clicks on 'Pay', we will redirect the user to ti.to for the payment and then when done the user will be redirected back to the order page in our site

**Comment by patrick91** [comment]
Closing this since TITO won't really support e-invoice :)
