### ISSUE TITLE
Grants form: validate the links/handles to avoid mistakes from users

### ISSUE THREAD

**Issue by estyxx** [pythonitalia/pycon#3997]
We don't validate the fields:

      website
      twitterHandle
      githubHandle
      linkedinUrl
      mastodonHandle

So people can add whatever they want, they always confused between handle and URL... This is causing issue in the internal review page.

**Comment by marcoacierno** [comment]
Can we discuss removing this information from Grant and reusing the existing Participant feature?

**Comment by estyxx** [comment]
Oh didn't thought about that! yes sure
