### ISSUE TITLE
Allow anonymous CFP submissions / tickets

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#572]
I think it would be cool for the user to send a submission or buy a ticket without creating an account first. It would really create a better experience I think, especially for smaller events

**Comment by patrick91** [comment]
I'm +1 on this :)

**Comment by patrick91** [comment]
@marcoacierno I put this as a EOY release, not for our CFP. Let me know if that's ok for you. I think for PyCon is ok to require registration :)

**Comment by marcoacierno** [comment]
OK for pycon, but I might need to implement this somehow for python pizza

**Comment by patrick91** [comment]
I'll close this for now :)
