### ISSUE TITLE
Add missing attributes to Submission model

### ISSUE THREAD

**Issue by greenkey** [pythonitalia/pycon#650]
List of missing information:
- [x] audience_level
- [ ] slug

**Comment by estyxx** [comment]
For Audience Level there is the PR [#609](https://github.com/pythonitalia/pycon/pull/609) 

I can integrate also "Slug" in the same?

P. S. What is "Slag"? seem similar to Elevator pitch??

**Comment by patrick91** [comment]
@estyxx slug is the url friendly version of a title, like:

Title: "Patrick is silly"
Slug: "patrick-is-silly" 

:)

**Comment by patrick91** [comment]
I was thinking that maybe we don't want slugs in submission, only in accepted talks :)

**Comment by marcoacierno** [comment]
How do we want to handle "accepted talks"? @patrick91 My idea was to not have a separate model or anything. Just that, if a ScheduleItem is created with a submission, it means that the submission is accepted.

We can also add the slug in the schedule item.

Do we have any special requirement that needs the submission to have an "accepted" state using a new model?

**Comment by patrick91** [comment]
> Do we have any special requirement that needs the submission to have an "accepted" state using a new model?

Don't think so :)

**Comment by estyxx** [comment]
Can we close this? Do we need the slug in the Submission model??
