### ISSUE TITLE
Unimported tables from old DB

### ISSUE THREAD

**Issue by greenkey** [pythonitalia/pycon#668]
Creating the import command I found some tables we don't import, we should discuss them in order to understand if they're still needed or not.

- Assopy
  - `country`, information about the countries (name, iso...)
  - `coupon` and `assopy_coupon_fares`, coupons!
  - `creditnote`, i think they were used to the reimbursements
  - `refund` and `refundorderitem`
  - `invoice` and `invoicelog`
  - `order` and `orderitem`, we actually import this but we miss some information: `card_name`, `recipient_code`, `country_id`, `pec_address`, `cf_code`, `address`, `vat_number`, `vat_id`
  - `token`, `user`, `useridentity`, `useroauthinfo`, seem all related to some user auth, do we still need these?
  - `vat` and `vatfare` to handle the VAT information
- Conference
  - `attendeeprofile`, `attendeelink`
  - `conferencetag`, `conferencetaggeditem`
  - `deadline`, `deadlinecontent`, we already have deadlines (from conference table), what's the purpose of these? They seems just descriptive
  - `didyouknow`
  - `event`, we import this but we miss some information like `tags`, `video`, `seats`, `sponsor_id`, `bookable`
  - `eventbooking`, `eventinterest`, they both link user and event, are we missing the feature in the new site?
  - `fare`, we import this but we miss information: `ticket_type`, `blob`, `payment_type`, `recipient_type`
  - `hotel`
  - `mediapartner`, `mediapartnerconference`
  - `multilingualcontent`, we already import the Submission/Talk description but we're not importing bios, messages and ad_hoc_description
  - `presence`
  - `quote`
  - `specialplace`
  - `sponsor`, `sponsorincome`
  - `startup`, `startupconference`
- Other
  - `email_template_email`
  - `jobboard_joboffer`
- P3
  - `donation`
  - `hotelbooking`, `hotelroom`, `ticketroom`
  - `p3profile`
  - `speakerconference`
  - `sprint`, `sprintpresence`
  - `ticketconference`, we are just importing `assigned_to` field, other than the questions (that we'll implement within a specific issue) there is also the `days` field, how are we implementing the day presence?
  - `ticketsim`

**Comment by estyxx** [comment]
I was looking at "country": In the new models about the User we don't have enough information now (only the username and email)... It should be improved maybe for statistics and invoices...

**Comment by marcoacierno** [comment]
What are two fields `sponsor, sponsorincome` in `Conference`?
