### ISSUE TITLE
[Global] Login

### ISSUE THREAD

**Issue by patrick91** [pythonitalia/pycon#807]
We need to allow users to login, not sure we already implemented this in the backend (@marcoacierno can you check)?

In any case for the frontend I'm guessing we need to implement the following:

- [ ] Login form
- [ ] Login mutation 
- [ ] Store JWT
- [ ] Refresh JWT
- [ ] Connection with Apollo

**Comment by marcoacierno** [comment]
I can see two login and register mutations, but we do not have a JWT system in place

**Comment by marcoacierno** [comment]
NOTE:

If you want to use the session-based login in the playground you've to change the `request.credentials` setting from `omit` to `same-origin` or `include`
