### ISSUE TITLE
[Global] Internationalisation 

### ISSUE THREAD

**Issue by patrick91** [pythonitalia/pycon#815]
Our current PyCon website supports multiple languages, we need to do the same :D

All the models with copy need be translatable, we also should specify a list of languages a conference accepts (for talks and also for the frontend).

For the frontend we should redirect the user to the appropriate language, netlify supports this: https://www.netlify.com/docs/redirects/#geoip-and-language-based-redirects
so we could have the root to redirect to /en or /it based on the user language preference :) not sure we can store a cookie for the preference but that's a minor thing I'd say.

**Comment by patrick91** [comment]
https://github.com/tatterdemalion/django-nece
https://github.com/zostera/django-modeltrans
https://github.com/raphaelm/django-i18nfield

**Comment by marcoacierno** [comment]
What library do you want to use?

**Comment by patrick91** [comment]
@marcoacierno I was trying https://github.com/raphaelm/django-i18nfield

seems good :)
