### ISSUE TITLE
Automatically re-stage formatted files by pre-commit?

### ISSUE THREAD

**Issue by estyxx** [pythonitalia/pycon#950]
Can we add a hook to re-stage at least the edited files by pre-commit?? Maybe add a custom hook?

This answer could be useful, but I have to look closer...
https://stackoverflow.com/questions/26886363/git-how-to-re-stage-the-staged-files-in-a-pre-commit-hook?noredirect=1

**Comment by patrick91** [comment]
Uhm, not sure it is a good idea, it is always good to check what the changes were, no? :)

**Comment by estyxx** [comment]
If you would do commit also I agree it's a very bad idea! But only re-stage the files I think it shouldn't make any damage... And you still have the possibility to check the files (of course I do). 
But, most of the times pre-commit reformat only with black/flake, I have nothing to correct, I pick up the reformatted files and re-add them to the index on by one... It's annoying a little bit... :'D
